In [1]:
import pandas as pd

In [34]:
fc_file = '../featureCounts/all_feature.txt'
df = pd.read_csv(fc_file,header=1,sep='\t')
df_geneid = df.iloc[:,0:1]
df_counts = df.iloc[:,6:]
df_merge = pd.concat([df_geneid,df_counts],axis=1)
df_merge

,Geneid,../bam/293T-RNASeq-2Mock-1_combined_Aligned_sort.bam,../bam/293T-RNASeq-2BE4-All-1_combined_Aligned_sort.bam,../bam/293T-RNASeq-2Vector-1_combined_Aligned_sort.bam,../bam/293T-RNASeq-BE4-1_combined_Aligned_sort.bam,../bam/293T-RNASeq-BE4-2_combined_Aligned_sort.bam,../bam/293T-RNASeq-EM-1_combined_Aligned_sort.bam,../bam/293T-RNASeq-EM-2_combined_Aligned_sort.bam,../bam/293T-RNASeq-BE4-0706-rep1_Aligned_sort.bam,../bam/293T-RNASeq-M2-0706-rep1_Aligned_sort.bam
0,ENSG00000223972.5,0,0,0,0,0,0,0,0,3
1,ENSG00000227232.5,359,211,283,340,453,471,622,532,616
2,ENSG00000278267.1,97,27,40,16,27,10,12,2,2
3,ENSG00000243485.5,0,0,0,0,0,0,0,0,0
4,ENSG00000284332.1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
58716,ENSG00000198695.2,62827,59665,84573,20121,29773,18084,20752,42700,41493
58717,ENSG00000210194.1,26,89,163,38,41,20,22,79,50
58718,ENSG00000198727.2,150882,111116,137347,166863,266336,145297,180634,189366,193208
58719,ENSG00000210195.2,7,19,28,18,13,11,8,17,8
58720,ENSG00000210196.2,1695,1945,2755,1624,2197,1538,1536,1260,1355

In [37]:
colName = ['Geneid','2Mock_1','2BE4ALL_1','2Vector_1','BE4_1','BE4_2','EM_1','EM_2','BE4_0706_1','M2_0706_1']

In [38]:
# df = df.copy()
df_merge.columns=colName
df_merge

,Geneid,2Mock_1,2BE4ALL_1,2Vector_1,BE4_1,BE4_2,EM_1,EM_2,BE4_0706_1,M2_0706_1
0,ENSG00000223972.5,0,0,0,0,0,0,0,0,3
1,ENSG00000227232.5,359,211,283,340,453,471,622,532,616
2,ENSG00000278267.1,97,27,40,16,27,10,12,2,2
3,ENSG00000243485.5,0,0,0,0,0,0,0,0,0
4,ENSG00000284332.1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
58716,ENSG00000198695.2,62827,59665,84573,20121,29773,18084,20752,42700,41493
58717,ENSG00000210194.1,26,89,163,38,41,20,22,79,50
58718,ENSG00000198727.2,150882,111116,137347,166863,266336,145297,180634,189366,193208
58719,ENSG00000210195.2,7,19,28,18,13,11,8,17,8
58720,ENSG00000210196.2,1695,1945,2755,1624,2197,1538,1536,1260,1355

In [41]:
df_merge.to_csv(fc_file.replace('.txt','_fix.csv'),index=None,sep='\t')